import Foundation

class SpeciesClass {
    class func writeFile(
        speciesName: String,
        portraitGroup: String,
        gendered: Bool,
        modDirectory: URL? = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    ) {
        let fileName = speciesName.replacingOccurrences(of: " ", with: "_").lowercased()

        FM.createFile(
            named: "\(fileName)_species_classes.txt",
            at:  modDirectory!.appendingPathComponent("common")
                              .appendingPathComponent("species_classes"),
            with: Data(content(speciesName: speciesName, portraitGroup: portraitGroup, gendered: gendered).utf8)
        )
    }

    private class func content(speciesName: String, portraitGroup: String, gendered: Bool) -> String {
        """
        ### Generated by SpeciesGenerator cli tool

        \(speciesName.capitalized) = {
            archetype = BIOLOGICAL
            possible = { authority = { NOT = { value = auth_machine_intelligence text = SPECIES_CLASS_MUST_NOT_USE_MACHINE_INTELLIGENCE } } }
            portraits = {
                "\(portraitGroup)"
            }
            gender = \(gendered ? "yes" : "no")
            graphical_culture = humanoid_01
            move_pop_sound_effect = "moving_pop_confirmation"
        }

        """
    }
}
