import Foundation

extension String {
    public static func speciesClasses(speciesName: String, portraitGroup: String, gendered: Bool) -> String {
        """
        ### Generated by SpeciesGenerator cli tool

        \(speciesName.capitalized) = {
            archetype = BIOLOGICAL
            possible = { authority = { NOT = { value = auth_machine_intelligence text = SPECIES_CLASS_MUST_NOT_USE_MACHINE_INTELLIGENCE } } }
            portraits = {
                "\(portraitGroup)"
            }
            gender = \(gendered ? "yes" : "no")
            graphical_culture = humanoid_01
            move_pop_sound_effect = "moving_pop_confirmation"
        }

        """
    }
}
